export * from "./checkIsOneCellShip";
export * from "./checkIsHorizontalShip";
export * from "./checkIsCellHasShip";
export * from "./checkIsShipDestroyed";
export * from "./markAroundShip";
export * from "./findShip";
export * from "./types";
export * from "./removeShipFromBoard";
export * from "./addShipToBoard";
